### ISSUE TITLE
Short writeup on how to install and run DOS Medley 2.0

### ISSUE THREAD

**Issue by alexshendi** [Interlisp/DOS#1]
This is my first draft of the promised HOWTO. 
New version, Links corrected.

[DOS.md](https://drive.google.com/file/d/1wrxjzrjytL_9EojHPTrEKTG8flHfKCuA/view?usp=drivesdk)

**Comment by masinter** [comment]
I've installed your DOS.md at the top of the DOS repo and linked to it from README.md.
I added a more general issue for context, but DOS has its own issue list.

Thank you @alexshendi
